"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConfigSystem = void 0;
const entity_type_1 = require("../enums/types/entity.type");
const item_type_1 = require("../enums/types/item.type");
class ConfigSystem {
    health;
    server;
    items;
    entityRadius;
    entityDamage;
    entityOnHitDamage;
    itemDamage;
    itemDefense;
    itemMobDefense;
    itemBuildingDamage;
    itemHarvest;
    itemDig;
    itemRadius;
    itemOffset;
    itemColdValue;
    itemWaterValue;
    itemHealValue;
    itemFoodValue;
    treasureDropChance;
    dropChance;
    seedBirth;
    seedLife;
    seedFruitsCount;
    seedFruits;
    seedGrowth;
    seedDrain;
    config;
    constructor(server) {
        this.server = server;
        this.config = server.config;
        this.items = [];
        const EntityIndex = Object.values(entity_type_1.EntityType)[Object.values(entity_type_1.EntityType).length - 1];
        const ItemIndex = Object.values(item_type_1.ItemType)[Object.values(item_type_1.ItemType).length - 1];
        this.health = new Array(EntityIndex).fill(0);
        this.entityDamage = new Array(EntityIndex).fill(0);
        this.entityOnHitDamage = new Array(EntityIndex).fill(0);
        this.entityRadius = new Array(EntityIndex).fill(25);
        this.seedBirth = new Array(EntityIndex).fill(0);
        this.seedGrowth = new Array(EntityIndex).fill(0);
        this.seedDrain = new Array(EntityIndex).fill(0);
        this.seedLife = new Array(EntityIndex).fill(0);
        this.seedFruitsCount = new Array(EntityIndex).fill(0);
        this.seedFruits = new Array(EntityIndex).fill(0);
        this.itemDefense = new Array(ItemIndex).fill(0);
        this.itemMobDefense = new Array(ItemIndex).fill(0);
        this.itemDamage = new Array(ItemIndex).fill(0);
        this.itemBuildingDamage = new Array(ItemIndex).fill(0);
        this.itemHarvest = new Array(ItemIndex).fill(0);
        this.itemDig = new Array(ItemIndex).fill(0);
        this.itemRadius = new Array(ItemIndex).fill(0);
        this.itemOffset = new Array(ItemIndex).fill(0);
        this.itemColdValue = new Array(ItemIndex).fill(0);
        this.itemFoodValue = new Array(ItemIndex).fill(0);
        this.itemWaterValue = new Array(ItemIndex).fill(0);
        this.itemHealValue = new Array(ItemIndex).fill(0);
        this.dropChance = new Array(ItemIndex).fill(0);
        this.treasureDropChance = new Array(ItemIndex).fill(0);
        this.setupChances();
        this.setupItems();
        this.setupDamage();
        this.setupCollide();
        this.setupRadius();
        this.setupHealth();
        this.setupSeeds();
        this.loadConfig();
    }
    loadConfig() {
        // const items = fs.readdirSync("./config/items");
        //
        // for (const fileName of items) {
        //     try {
        //         const config = JSON.parse(fs.readFileSync("./config/items/" + fileName, "utf-8"));
        //         const name = fileName.replace(/\.json$/g, "");
        //         const item = ItemType[name.toUpperCase()];
        //         if (item === undefined) {
        //             this.server.logger.warn("Invalid type in item config: " + name);
        //             continue;
        //         }
        //
        //         this.server.logger.log("Loaded item with name: " + name + " and type: " + item);
        //         this.items[item] = config;
        //     } catch (e) {
        //         this.server.logger.error(e);
        //     }
        // }
    }
    setupItems() {
        this.itemDefense[item_type_1.ItemType.WOOD_HELMET] = this.config.wood_helmet_defense ?? -1;
        this.itemDefense[item_type_1.ItemType.STONE_HELMET] = this.config.stone_helmet_defense ?? -2;
        this.itemDefense[item_type_1.ItemType.GOLD_HELMET] = this.config.gold_helmet_defense ?? -4;
        this.itemDefense[item_type_1.ItemType.DIAMOND_HELMET] = this.config.diamond_helmet_defense ?? -5;
        this.itemDefense[item_type_1.ItemType.CRAB_HELMET] = this.config.crab_helmet_defense ?? -5;
        this.itemDefense[item_type_1.ItemType.AMETHYST_HELMET] = this.config.amethyst_helmet_defense ?? -6;
        this.itemDefense[item_type_1.ItemType.REIDITE_HELMET] = this.config.reidite_helmet_defense ?? -7;
        this.itemDefense[item_type_1.ItemType.DRAGON_HELMET] = this.config.dragon_helmet_defense ?? -8;
        this.itemDefense[item_type_1.ItemType.LAVA_HELMET] = this.config.lava_helmet_defense ?? -9;
        this.itemDefense[item_type_1.ItemType.WOOD_SHIELD] = this.config.wood_shield_defense ?? 1;
        this.itemDefense[item_type_1.ItemType.STONE_SHIELD] = this.config.stone_shield_defense ?? 2;
        this.itemDefense[item_type_1.ItemType.GOLD_SHIELD] = this.config.gold_shield_defense ?? 3;
        this.itemDefense[item_type_1.ItemType.DIAMOND_SHIELD] = this.config.diamond_shield_defense ?? 4;
        this.itemDefense[item_type_1.ItemType.AMETHYST_SHIELD] = this.config.amethyst_shield_defense ?? 5;
        this.itemDefense[item_type_1.ItemType.REIDITE_SHIELD] = this.config.reidite_shield_defense ?? 6;
        this.itemDefense[item_type_1.ItemType.HOOD] = this.config.hood_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.WINTER_HOOD] = this.config.winter_hood_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.PEASANT] = this.config.peasant_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.WINTER_PEASANT] = this.config.winter_peasant_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.DIVING_MASK] = this.config.diving_mask_defense ?? 2;
        this.itemDefense[item_type_1.ItemType.SUPER_DIVING_SUIT] = this.config.super_diving_suit_defense ?? 4;
        this.itemDefense[item_type_1.ItemType.DIAMOND_PROTECTION] = this.config.warm_protection_defense ?? 2;
        this.itemDefense[item_type_1.ItemType.AMETHYST_PROTECTION] = this.config.warm_protection2_defense ?? 4;
        this.itemDefense[item_type_1.ItemType.REIDITE_PROTECTION] = this.config.warm_protection3_defense ?? 6;
        this.itemDefense[item_type_1.ItemType.EARMUFFS] = this.config.earmuff_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.COAT] = this.config.coat_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.CAP_SCARF] = this.config.scarf_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.FUR_HAT] = this.config.fur_hat_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.CROWN_GREEN] = this.config.green_crown_defense ?? 4;
        this.itemDefense[item_type_1.ItemType.CROWN_BLUE] = this.config.blue_crown_defense ?? 4;
        this.itemDefense[item_type_1.ItemType.CROWN_ORANGE] = this.config.orange_crown_defense ?? 4;
        this.itemDefense[item_type_1.ItemType.EXPLORER_HAT] = this.config.explorer_hat_defense ?? 0;
        this.itemDefense[item_type_1.ItemType.PIRATE_HAT] = this.config.pirate_hat_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.EXPLORER_HAT] = this.config.explorer_hat_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.PIRATE_HAT] = this.config.pirate_hat_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.CROWN_GREEN] = this.config.green_crown_mob_defense ?? 4;
        this.itemMobDefense[item_type_1.ItemType.CROWN_BLUE] = this.config.blue_crown_mob_defense ?? 4;
        this.itemMobDefense[item_type_1.ItemType.CROWN_ORANGE] = this.config.orange_crown_mob_defense ?? 4;
        this.itemMobDefense[item_type_1.ItemType.EARMUFFS] = this.config.earmuff_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.COAT] = this.config.coat_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.CAP_SCARF] = this.config.scarf_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.FUR_HAT] = this.config.fur_hat_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.DIAMOND_PROTECTION] = this.config.warm_protection_mob_defense ?? 8;
        this.itemMobDefense[item_type_1.ItemType.AMETHYST_PROTECTION] = this.config.warm_protection2_mob_defense ?? 13;
        this.itemMobDefense[item_type_1.ItemType.REIDITE_PROTECTION] = this.config.warm_protection3_mob_defense ?? 19;
        this.itemMobDefense[item_type_1.ItemType.DIVING_MASK] = this.config.diving_mask_mob_defense ?? 2;
        this.itemMobDefense[item_type_1.ItemType.SUPER_DIVING_SUIT] = this.config.super_diving_suit_mob_defense ?? 16;
        this.itemMobDefense[item_type_1.ItemType.HOOD] = this.config.hood_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.WINTER_HOOD] = this.config.winter_hood_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.PEASANT] = this.config.peasant_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.WINTER_PEASANT] = this.config.winter_peasant_mob_defense ?? 0;
        this.itemMobDefense[item_type_1.ItemType.WOOD_SHIELD] = this.config.wood_shield_defense_monster ?? 4;
        this.itemMobDefense[item_type_1.ItemType.STONE_SHIELD] = this.config.stone_shield_defense_monster ?? 8;
        this.itemMobDefense[item_type_1.ItemType.GOLD_SHIELD] = this.config.gold_shield_defense_monster ?? 12;
        this.itemMobDefense[item_type_1.ItemType.DIAMOND_SHIELD] = this.config.diamond_shield_defense_monster ?? 16;
        this.itemMobDefense[item_type_1.ItemType.AMETHYST_SHIELD] = this.config.amethyst_shield_defense_monster ?? 20;
        this.itemMobDefense[item_type_1.ItemType.REIDITE_SHIELD] = this.config.reidite_shield_defense_monster ?? 24;
        this.itemMobDefense[item_type_1.ItemType.WOOD_HELMET] = this.config.wood_helmet_mob_defense ?? -4;
        this.itemMobDefense[item_type_1.ItemType.STONE_HELMET] = this.config.stone_helmet_mob_defense ?? -8;
        this.itemMobDefense[item_type_1.ItemType.GOLD_HELMET] = this.config.gold_helmet_mob_defense ?? -13;
        this.itemMobDefense[item_type_1.ItemType.DIAMOND_HELMET] = this.config.diamond_helmet_mob_defense ?? -19;
        this.itemMobDefense[item_type_1.ItemType.CRAB_HELMET] = this.config.crab_helmet_defense ?? -19;
        this.itemMobDefense[item_type_1.ItemType.AMETHYST_HELMET] = this.config.amethyst_helmet_mob_defense ?? -23;
        this.itemMobDefense[item_type_1.ItemType.REIDITE_HELMET] = this.config.reidite_helmet_mob_defense ?? -25;
        this.itemMobDefense[item_type_1.ItemType.DRAGON_HELMET] = this.config.dragon_helmet_mob_defense ?? -27;
        this.itemMobDefense[item_type_1.ItemType.LAVA_HELMET] = this.config.lava_helmet_mob_defense ?? -30;
        this.itemDamage[item_type_1.ItemType.HAND] = this.config.hand_damage ?? 5;
        this.itemDamage[item_type_1.ItemType.MACHETE] = this.config.hand_damage ?? 5;
        this.itemDamage[item_type_1.ItemType.WOOD_SWORD] = this.config.wood_sword_damage ?? 12;
        this.itemDamage[item_type_1.ItemType.STONE_SWORD] = this.config.stone_sword_damage ?? 19;
        this.itemDamage[item_type_1.ItemType.GOLD_SWORD] = this.config.gold_sword_damage ?? 22;
        this.itemDamage[item_type_1.ItemType.DIAMOND_SWORD] = this.config.diamond_sword_damage ?? 24;
        this.itemDamage[item_type_1.ItemType.PIRATE_SWORD] = this.config.pirate_sword_damage ?? 24;
        this.itemDamage[item_type_1.ItemType.AMETHYST_SWORD] = this.config.amethyst_sword_damage ?? 27;
        this.itemDamage[item_type_1.ItemType.REIDITE_SWORD] = this.config.reidite_sword_damage ?? 30;
        this.itemDamage[item_type_1.ItemType.DRAGON_SWORD] = this.config.dragon_sword_damage ?? 30;
        this.itemDamage[item_type_1.ItemType.LAVA_SWORD] = this.config.lava_sword_damage ?? 33;
        this.itemDamage[item_type_1.ItemType.CURSED_SWORD] = this.config.cursed_sword_damage ?? 4e13;
        this.itemDamage[item_type_1.ItemType.WOOD_SPEAR] = this.config.wood_spear_damage ?? 10;
        this.itemDamage[item_type_1.ItemType.CRAB_SPEAR] = this.config.crab_spear_damage ?? 14;
        this.itemDamage[item_type_1.ItemType.STONE_SPEAR] = this.config.stone_spear_damage ?? 14;
        this.itemDamage[item_type_1.ItemType.GOLD_SPEAR] = this.config.gold_spear_damage ?? 15;
        this.itemDamage[item_type_1.ItemType.DIAMOND_SPEAR] = this.config.diamond_spear_damage ?? 17;
        this.itemDamage[item_type_1.ItemType.AMETHYST_SPEAR] = this.config.amethyst_spear_damage ?? 18;
        this.itemDamage[item_type_1.ItemType.REIDITE_SPEAR] = this.config.reidite_spear_damage ?? 22;
        this.itemDamage[item_type_1.ItemType.DRAGON_SPEAR] = this.config.dragon_spear_damage ?? 22;
        this.itemDamage[item_type_1.ItemType.LAVA_SPEAR] = this.config.lava_spear_damage ?? 24;
        this.itemDamage[item_type_1.ItemType.WOOD_PICK] = 1;
        this.itemDamage[item_type_1.ItemType.STONE_PICK] = 2;
        this.itemDamage[item_type_1.ItemType.GOLD_PICK] = 3;
        this.itemDamage[item_type_1.ItemType.DIAMOND_PICK] = 4;
        this.itemDamage[item_type_1.ItemType.AMETHYST_PICK] = 5;
        this.itemDamage[item_type_1.ItemType.REIDITE_PICK] = 6;
        this.itemDamage[item_type_1.ItemType.WOOD_SHIELD] = 1;
        this.itemDamage[item_type_1.ItemType.STONE_SHIELD] = 2;
        this.itemDamage[item_type_1.ItemType.GOLD_SHIELD] = 3;
        this.itemDamage[item_type_1.ItemType.DIAMOND_SHIELD] = 4;
        this.itemDamage[item_type_1.ItemType.AMETHYST_SHIELD] = 5;
        this.itemDamage[item_type_1.ItemType.REIDITE_SHIELD] = 6;
        this.itemDamage[item_type_1.ItemType.STONE_HAMMER] = this.config.stone_hammer_damage ?? 2;
        this.itemDamage[item_type_1.ItemType.GOLD_HAMMER] = this.config.gold_hammer_damage ?? 3;
        this.itemDamage[item_type_1.ItemType.DIAMOND_HAMMER] = this.config.diamond_hammer_damage ?? 4;
        this.itemDamage[item_type_1.ItemType.AMETHYST_HAMMER] = this.config.amethyst_hammer_damage ?? 5;
        this.itemDamage[item_type_1.ItemType.REIDITE_HAMMER] = this.config.reidite_hammer_damage ?? 6;
        this.itemDamage[item_type_1.ItemType.SUPER_HAMMER] = this.config.super_hammer_damage ?? 12;
        this.itemBuildingDamage[item_type_1.ItemType.STONE_HAMMER] = this.config.stone_hammer_building_damage ?? 20;
        this.itemBuildingDamage[item_type_1.ItemType.GOLD_HAMMER] = this.config.gold_hammer_building_damage ?? 30;
        this.itemBuildingDamage[item_type_1.ItemType.DIAMOND_HAMMER] = this.config.diamond_hammer_building_damage ?? 40;
        this.itemBuildingDamage[item_type_1.ItemType.AMETHYST_HAMMER] = this.config.amethyst_hammer_building_damage ?? 50;
        this.itemBuildingDamage[item_type_1.ItemType.REIDITE_HAMMER] = this.config.reidite_hammer_building_damage ?? 60;
        this.itemBuildingDamage[item_type_1.ItemType.SUPER_HAMMER] = this.config.super_hammer_building_damage ?? 70;
        this.itemBuildingDamage[item_type_1.ItemType.CURSED_SWORD] = this.config.cursed_sword_damage ?? 4e13;
        this.itemBuildingDamage[item_type_1.ItemType.WRENCH] = this.config.wrench ?? 70;
        this.itemDamage[item_type_1.ItemType.BOOK] = 1;
        this.itemDamage[item_type_1.ItemType.WATERING_CAN_FULL] = 1;
        this.itemDamage[item_type_1.ItemType.WRENCH] = 2;
        this.itemHarvest[item_type_1.ItemType.HAND] = 1;
        this.itemHarvest[item_type_1.ItemType.WOOD_PICK] = 2;
        this.itemHarvest[item_type_1.ItemType.STONE_PICK] = 3;
        this.itemHarvest[item_type_1.ItemType.GOLD_PICK] = 4;
        this.itemHarvest[item_type_1.ItemType.DIAMOND_PICK] = 5;
        this.itemHarvest[item_type_1.ItemType.AMETHYST_PICK] = 6;
        this.itemHarvest[item_type_1.ItemType.REIDITE_PICK] = 7;
        this.itemDig[item_type_1.ItemType.STONE_SHOVEL] = this.config.stone_shovel_dig ?? 1;
        this.itemDig[item_type_1.ItemType.GOLD_SHOVEL] = this.config.gold_shovel_dig ?? 2;
        this.itemDig[item_type_1.ItemType.DIAMOND_SHOVEL] = this.config.diamond_shovel_dig ?? 3;
        this.itemDig[item_type_1.ItemType.AMETHYST_SHOVEL] = this.config.amethyst_shovel_dig ?? 4;
        this.itemDig[item_type_1.ItemType.REIDITE_SHOVEL] = this.config.reidite_shovel_dig ?? 5;
        this.itemRadius[item_type_1.ItemType.WOOD_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.STONE_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.GOLD_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.DIAMOND_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.AMETHYST_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.REIDITE_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.DRAGON_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.LAVA_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.CURSED_SWORD] = 45;
        this.itemRadius[item_type_1.ItemType.PIRATE_SWORD] = 48;
        this.itemRadius[item_type_1.ItemType.WOOD_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.STONE_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.GOLD_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.DIAMOND_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.AMETHYST_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.REIDITE_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.REIDITE_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.CRAB_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.DRAGON_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.LAVA_SPEAR] = 60;
        this.itemRadius[item_type_1.ItemType.WOOD_PICK] = 60;
        this.itemRadius[item_type_1.ItemType.STONE_PICK] = 60;
        this.itemRadius[item_type_1.ItemType.GOLD_PICK] = 60;
        this.itemRadius[item_type_1.ItemType.DIAMOND_PICK] = 60;
        this.itemRadius[item_type_1.ItemType.AMETHYST_PICK] = 60;
        this.itemRadius[item_type_1.ItemType.REIDITE_PICK] = 60;
        this.itemRadius[item_type_1.ItemType.STONE_HAMMER] = 60;
        this.itemRadius[item_type_1.ItemType.GOLD_HAMMER] = 60;
        this.itemRadius[item_type_1.ItemType.DIAMOND_HAMMER] = 60;
        this.itemRadius[item_type_1.ItemType.AMETHYST_HAMMER] = 60;
        this.itemRadius[item_type_1.ItemType.REIDITE_HAMMER] = 60;
        this.itemRadius[item_type_1.ItemType.SUPER_HAMMER] = 60;
        this.itemRadius[item_type_1.ItemType.STONE_SHOVEL] = 45;
        this.itemRadius[item_type_1.ItemType.GOLD_SHOVEL] = 45;
        this.itemRadius[item_type_1.ItemType.DIAMOND_SHOVEL] = 45;
        this.itemRadius[item_type_1.ItemType.AMETHYST_SHOVEL] = 45;
        this.itemRadius[item_type_1.ItemType.REIDITE_SHOVEL] = 45;
        this.itemRadius[item_type_1.ItemType.BOOK] = 45;
        this.itemRadius[item_type_1.ItemType.WRENCH] = 62;
        this.itemRadius[item_type_1.ItemType.WATERING_CAN_EMPTY] = 45;
        this.itemRadius[item_type_1.ItemType.WATERING_CAN_FULL] = 45;
        this.itemRadius[item_type_1.ItemType.MACHETE] = 45;
        this.itemRadius[item_type_1.ItemType.PITCHFORK] = 90;
        this.itemRadius[item_type_1.ItemType.GOLD_PITCHFORK] = 90;
        this.itemRadius[item_type_1.ItemType.WOOD_SHIELD] = 40;
        this.itemRadius[item_type_1.ItemType.STONE_SHIELD] = 40;
        this.itemRadius[item_type_1.ItemType.GOLD_SHIELD] = 40;
        this.itemRadius[item_type_1.ItemType.DIAMOND_SHIELD] = 40;
        this.itemRadius[item_type_1.ItemType.AMETHYST_SHIELD] = 40;
        this.itemRadius[item_type_1.ItemType.REIDITE_SHIELD] = 40;
        this.itemRadius[item_type_1.ItemType.HAND] = 22;
        this.itemOffset[item_type_1.ItemType.HAND] = 20;
        this.itemOffset[item_type_1.ItemType.WOOD_SHIELD] = 20;
        this.itemOffset[item_type_1.ItemType.STONE_SHIELD] = 20;
        this.itemOffset[item_type_1.ItemType.GOLD_SHIELD] = 20;
        this.itemOffset[item_type_1.ItemType.DIAMOND_SHIELD] = 20;
        this.itemOffset[item_type_1.ItemType.AMETHYST_SHIELD] = 20;
        this.itemOffset[item_type_1.ItemType.REIDITE_SHIELD] = 20;
        this.itemOffset[item_type_1.ItemType.PITCHFORK] = 130;
        this.itemOffset[item_type_1.ItemType.GOLD_PITCHFORK] = 130;
        this.itemOffset[item_type_1.ItemType.WRENCH] = 50;
        this.itemOffset[item_type_1.ItemType.WATERING_CAN_EMPTY] = 50;
        this.itemOffset[item_type_1.ItemType.WATERING_CAN_FULL] = 50;
        this.itemOffset[item_type_1.ItemType.MACHETE] = 50;
        this.itemOffset[item_type_1.ItemType.BOOK] = 50;
        this.itemOffset[item_type_1.ItemType.STONE_SHOVEL] = 50;
        this.itemOffset[item_type_1.ItemType.GOLD_SHOVEL] = 50;
        this.itemOffset[item_type_1.ItemType.DIAMOND_SHOVEL] = 50;
        this.itemOffset[item_type_1.ItemType.AMETHYST_SHOVEL] = 50;
        this.itemOffset[item_type_1.ItemType.REIDITE_SHOVEL] = 50;
        this.itemOffset[item_type_1.ItemType.STONE_HAMMER] = 50;
        this.itemOffset[item_type_1.ItemType.GOLD_HAMMER] = 50;
        this.itemOffset[item_type_1.ItemType.DIAMOND_HAMMER] = 50;
        this.itemOffset[item_type_1.ItemType.AMETHYST_HAMMER] = 50;
        this.itemOffset[item_type_1.ItemType.REIDITE_HAMMER] = 50;
        this.itemOffset[item_type_1.ItemType.SUPER_HAMMER] = 50;
        this.itemOffset[item_type_1.ItemType.WOOD_PICK] = 50;
        this.itemOffset[item_type_1.ItemType.STONE_PICK] = 50;
        this.itemOffset[item_type_1.ItemType.GOLD_PICK] = 50;
        this.itemOffset[item_type_1.ItemType.DIAMOND_PICK] = 50;
        this.itemOffset[item_type_1.ItemType.AMETHYST_PICK] = 50;
        this.itemOffset[item_type_1.ItemType.REIDITE_PICK] = 50;
        this.itemOffset[item_type_1.ItemType.WOOD_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.STONE_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.GOLD_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.DIAMOND_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.AMETHYST_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.REIDITE_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.REIDITE_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.CRAB_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.DRAGON_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.LAVA_SPEAR] = 110;
        this.itemOffset[item_type_1.ItemType.WOOD_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.STONE_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.GOLD_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.DIAMOND_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.AMETHYST_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.REIDITE_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.DRAGON_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.LAVA_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.CURSED_SWORD] = 65;
        this.itemOffset[item_type_1.ItemType.PIRATE_SWORD] = 68;
        this.itemFoodValue[item_type_1.ItemType.BERRY] = 10;
        this.itemFoodValue[item_type_1.ItemType.CRAB_LOOT] = 10;
        this.itemFoodValue[item_type_1.ItemType.GARLIC] = 14;
        this.itemFoodValue[item_type_1.ItemType.BREAD] = 15;
        this.itemFoodValue[item_type_1.ItemType.MEAT] = 15;
        this.itemFoodValue[item_type_1.ItemType.WATERMELON] = 15;
        this.itemFoodValue[item_type_1.ItemType.TOMATO] = 16;
        this.itemFoodValue[item_type_1.ItemType.FISH] = 18;
        this.itemFoodValue[item_type_1.ItemType.CARROT] = 20;
        this.itemFoodValue[item_type_1.ItemType.CACTUS] = 20;
        this.itemFoodValue[item_type_1.ItemType.WATERMELON] = 20;
        this.itemFoodValue[item_type_1.ItemType.CRAB_STICK] = 20;
        this.itemFoodValue[item_type_1.ItemType.FISH_COOKED] = 35;
        this.itemFoodValue[item_type_1.ItemType.COOKED_MEAT] = 35;
        this.itemFoodValue[item_type_1.ItemType.COOKIE] = 50;
        this.itemFoodValue[item_type_1.ItemType.SANDWICH] = 100;
        this.itemFoodValue[item_type_1.ItemType.SUGAR_CAN] = 100;
        this.itemFoodValue[item_type_1.ItemType.CAKE] = 100;
        this.itemColdValue[item_type_1.ItemType.ICE] = 20;
        this.itemWaterValue[item_type_1.ItemType.WATERMELON] = 8;
        this.itemWaterValue[item_type_1.ItemType.BOTTLE_FULL] = 50;
        this.itemHealValue[item_type_1.ItemType.BANDAGE] = this.config.bandage_heal_effect ?? 5;
        this.itemHealValue[item_type_1.ItemType.ALOE_VERA] += 1;
        this.itemHealValue[item_type_1.ItemType.GARLIC] += 1;
    }
    setupChances() {
        this.dropChance[item_type_1.ItemType.STONE] = 4;
        this.dropChance[item_type_1.ItemType.GOLD] = 1;
        this.dropChance[item_type_1.ItemType.DIAMOND] = 0.5;
        this.treasureDropChance[item_type_1.ItemType.SUPER_HAMMER] = 0.05;
        this.treasureDropChance[item_type_1.ItemType.SUPER_DIVING_SUIT] = 0.05;
        this.treasureDropChance[item_type_1.ItemType.PIRATE_SWORD] = 0.3;
        this.treasureDropChance[item_type_1.ItemType.DIVING_MASK] = 0.5;
        this.treasureDropChance[item_type_1.ItemType.BOAT] = 1;
        this.treasureDropChance[item_type_1.ItemType.PAPER] = 1;
        this.treasureDropChance[item_type_1.ItemType.SAND] = 5;
        this.treasureDropChance[item_type_1.ItemType.GROUND] = 5;
        this.treasureDropChance[item_type_1.ItemType.AMETHYST_PICK] = 0.6;
        this.treasureDropChance[item_type_1.ItemType.DIAMOND_PICK] = 1.2;
        this.treasureDropChance[item_type_1.ItemType.GOLD_PICK] = 2;
        this.treasureDropChance[item_type_1.ItemType.STONE_PICK] = 2.4;
        this.treasureDropChance[item_type_1.ItemType.WOOD_PICK] = 3;
        this.treasureDropChance[item_type_1.ItemType.AMETHYST_SWORD] = 0.6;
        this.treasureDropChance[item_type_1.ItemType.DIAMOND_SWORD] = 1.2;
        this.treasureDropChance[item_type_1.ItemType.GOLD_SWORD] = 2;
        this.treasureDropChance[item_type_1.ItemType.STONE_SWORD] = 2.4;
        this.treasureDropChance[item_type_1.ItemType.WOOD_SWORD] = 3;
        this.treasureDropChance[item_type_1.ItemType.AMETHYST_SPEAR] = 0.6;
        this.treasureDropChance[item_type_1.ItemType.DIAMOND_SPEAR] = 1.2;
        this.treasureDropChance[item_type_1.ItemType.GOLD_SPEAR] = 2;
        this.treasureDropChance[item_type_1.ItemType.STONE_SPEAR] = 2.4;
        this.treasureDropChance[item_type_1.ItemType.WOOD_SPEAR] = 3;
        this.treasureDropChance[item_type_1.ItemType.BREAD_OVEN] = 1;
        this.treasureDropChance[item_type_1.ItemType.WINDMILL] = 1;
        this.treasureDropChance[item_type_1.ItemType.FURNACE] = 1;
        this.treasureDropChance[item_type_1.ItemType.WELL] = 1;
        this.treasureDropChance[item_type_1.ItemType.REIDITE_SPIKE] = 0.05;
        this.treasureDropChance[item_type_1.ItemType.REIDITE_WALL] = 0.1;
        this.treasureDropChance[item_type_1.ItemType.REIDITE_DOOR] = 0.1;
        this.treasureDropChance[item_type_1.ItemType.AMETHYST_SPIKE] = 0.1;
        this.treasureDropChance[item_type_1.ItemType.AMETHYST_WALL] = 0.15;
        this.treasureDropChance[item_type_1.ItemType.AMETHYST_DOOR] = 0.15;
        this.treasureDropChance[item_type_1.ItemType.DIAMOND_SPIKE] = 0.2;
        this.treasureDropChance[item_type_1.ItemType.DIAMOND_WALL] = 0.25;
        this.treasureDropChance[item_type_1.ItemType.DIAMOND_DOOR] = 0.25;
        this.treasureDropChance[item_type_1.ItemType.GOLD_SPIKE] = 0.25;
        this.treasureDropChance[item_type_1.ItemType.GOLD_WALL] = 0.3;
        this.treasureDropChance[item_type_1.ItemType.GOLD_DOOR] = 0.3;
        this.treasureDropChance[item_type_1.ItemType.STONE_SPIKE] = 0.35;
        this.treasureDropChance[item_type_1.ItemType.STONE_DOOR] = 0.35;
        this.treasureDropChance[item_type_1.ItemType.STONE_WALL] = 0.4;
        this.treasureDropChance[item_type_1.ItemType.WOOD_SPIKE] = 0.45;
        this.treasureDropChance[item_type_1.ItemType.WOOD_DOOR] = 0.5;
        this.treasureDropChance[item_type_1.ItemType.WOOD_WALL] = 0.5;
    }
    setupSeeds() {
        this.seedBirth[entity_type_1.EntityType.BERRY_SEED] = this.config.born_berry ?? 120000; // 2 min
        this.seedBirth[entity_type_1.EntityType.WHEAT_SEED] = this.config.born_wheat ?? 120000;
        this.seedBirth[entity_type_1.EntityType.PUMPKIN_SEED] = this.config.born_pumpkin ?? 160000;
        this.seedBirth[entity_type_1.EntityType.CARROT_SEED] = this.config.born_carrot ?? 240000;
        this.seedBirth[entity_type_1.EntityType.TOMATO_SEED] = this.config.born_tomato ?? 240000;
        this.seedBirth[entity_type_1.EntityType.THORNBUSH_SEED] = this.config.born_thornbush ?? 240000;
        this.seedBirth[entity_type_1.EntityType.GARLIC_SEED] = this.config.born_garlic ?? 160000;
        this.seedBirth[entity_type_1.EntityType.WATERMELON_SEED] = this.config.born_watermelon ?? 120000;
        this.seedDrain[entity_type_1.EntityType.BERRY_SEED] = this.config.water_berry ?? 200000;
        this.seedDrain[entity_type_1.EntityType.WHEAT_SEED] = this.config.water_wheat ?? 200000;
        this.seedDrain[entity_type_1.EntityType.PUMPKIN_SEED] = this.config.water_pumpkin ?? 250000;
        this.seedDrain[entity_type_1.EntityType.CARROT_SEED] = this.config.water_carrot ?? 200000;
        this.seedDrain[entity_type_1.EntityType.TOMATO_SEED] = this.config.water_tomato ?? 200000;
        this.seedDrain[entity_type_1.EntityType.THORNBUSH_SEED] = this.config.water_thornbush ?? 240000;
        this.seedDrain[entity_type_1.EntityType.GARLIC_SEED] = this.config.water_garlic ?? 200000;
        this.seedDrain[entity_type_1.EntityType.WATERMELON_SEED] = this.config.water_watermelon ?? 200000;
        this.seedGrowth[entity_type_1.EntityType.BERRY_SEED] = this.config.grown_berry ?? 40000;
        this.seedGrowth[entity_type_1.EntityType.WHEAT_SEED] = this.config.grown_wheat ?? 16000;
        this.seedGrowth[entity_type_1.EntityType.PUMPKIN_SEED] = this.config.grown_pumpkin ?? 50000;
        this.seedGrowth[entity_type_1.EntityType.CARROT_SEED] = this.config.grown_carrot ?? 30000;
        this.seedGrowth[entity_type_1.EntityType.TOMATO_SEED] = this.config.grown_tomato ?? 30000;
        this.seedGrowth[entity_type_1.EntityType.THORNBUSH_SEED] = this.config.grown_thornbush ?? 15000;
        this.seedGrowth[entity_type_1.EntityType.GARLIC_SEED] = this.config.grown_garlic ?? 120000;
        this.seedGrowth[entity_type_1.EntityType.WATERMELON_SEED] = this.config.grown_watermelon ?? 40000;
        this.seedLife[entity_type_1.EntityType.BERRY_SEED] = this.config.time_life_berry ?? 384e4; // 8 days in starve
        this.seedLife[entity_type_1.EntityType.WHEAT_SEED] = this.config.time_life_wheat ?? 384e4;
        this.seedLife[entity_type_1.EntityType.PUMPKIN_SEED] = this.config.time_life_pumpkin ?? 384e4;
        this.seedLife[entity_type_1.EntityType.CARROT_SEED] = this.config.time_life_carrot ?? 384e4;
        this.seedLife[entity_type_1.EntityType.TOMATO_SEED] = this.config.time_life_tomato ?? 384e4;
        this.seedLife[entity_type_1.EntityType.THORNBUSH_SEED] = this.config.time_life_thornbush ?? 384e4;
        this.seedLife[entity_type_1.EntityType.GARLIC_SEED] = this.config.time_life_garlic ?? 384e4;
        this.seedLife[entity_type_1.EntityType.WATERMELON_SEED] = this.config.time_life_watermelon ?? 384e4;
        this.seedFruitsCount[entity_type_1.EntityType.BERRY_SEED] = 3;
        this.seedFruitsCount[entity_type_1.EntityType.WHEAT_SEED] = 1;
        this.seedFruitsCount[entity_type_1.EntityType.PUMPKIN_SEED] = 1;
        this.seedFruitsCount[entity_type_1.EntityType.CARROT_SEED] = 1;
        this.seedFruitsCount[entity_type_1.EntityType.TOMATO_SEED] = 3;
        this.seedFruitsCount[entity_type_1.EntityType.THORNBUSH_SEED] = 1;
        this.seedFruitsCount[entity_type_1.EntityType.GARLIC_SEED] = 1;
        this.seedFruitsCount[entity_type_1.EntityType.WATERMELON_SEED] = 1;
        this.seedFruits[entity_type_1.EntityType.BERRY_SEED] = item_type_1.ItemType.BERRY;
        this.seedFruits[entity_type_1.EntityType.WHEAT_SEED] = item_type_1.ItemType.WHEAT;
        this.seedFruits[entity_type_1.EntityType.PUMPKIN_SEED] = item_type_1.ItemType.PUMPKIN;
        this.seedFruits[entity_type_1.EntityType.CARROT_SEED] = item_type_1.ItemType.CARROT;
        this.seedFruits[entity_type_1.EntityType.TOMATO_SEED] = item_type_1.ItemType.TOMATO;
        this.seedFruits[entity_type_1.EntityType.THORNBUSH_SEED] = item_type_1.ItemType.THORNBUSH;
        this.seedFruits[entity_type_1.EntityType.GARLIC_SEED] = item_type_1.ItemType.GARLIC;
        this.seedFruits[entity_type_1.EntityType.WATERMELON_SEED] = item_type_1.ItemType.WATERMELON;
    }
    // public setupSpeed() {
    //     this.speed[EntityType.PLAYER] = this.config.speed ?? 0.24;
    //     this.speed[EntityType.WOLF] = this.config.speed_wolf ?? 0.230;
    //     this.speed[EntityType.SPIDER] = this.config.speed_spider ?? 0.240;
    //     this.speed[EntityType.FOX] = this.config.speed_fox ?? 0.235;
    //     this.speed[EntityType.BEAR] = this.config.speed_bear ?? 0.220;
    //     this.speed[EntityType.DRAGON] = this.config.speed_dragon ?? 0.225;
    //     this.speed[EntityType.PIRANHA] = this.config.speed_piranha ?? 0.290;
    //     this.speed[EntityType.KRAKEN] = this.config.speed_kraken ?? 0.240;
    //     this.speed[EntityType.CRAB] = this.config.speed_crab ?? 0.320;
    //     this.speed[EntityType.FLAME] = this.config.speed_flame ?? 0.240;
    //     this.speed[EntityType.LAVA_DRAGON] = this.config.speed_lava_dragon ?? 0.245;
    //     this.speed[EntityType.BOAR] = this.config.speed_boar ?? 0.300;
    //     this.speed[EntityType.CRAB_BOSS] = this.config.speed_king_crab ?? 0.240;
    //     this.speed[EntityType.BABY_DRAGON] = this.config.speed_baby_dragon ?? 0.250;
    //     this.speed[EntityType.BABY_LAVA] = this.config.speed_baby_lava ?? 0.270;
    //     this.speed[EntityType.HAWK] = this.config.speed_hawk ?? 0.300;
    //     this.speed[EntityType.VULTURE] = this.config.speed_vulture ?? 0.250;
    //     this.speed[EntityType.SAND_WORM] = this.config.speed_sand_worm ?? 0.250;
    //     this.speed[EntityType.BABY_MAMMOTH] = this.config.speed_baby_mammoth ?? 0.230;
    //     this.speed[EntityType.MAMMOTH] = this.config.speed_mammoth ?? 0.230;
    //     this.speed[EntityType.RABBIT] = this.config.speed_rabbit ?? 0.320;
    //     this.speed[EntityType.PENGUIN] = this.config.speed_penguin ?? 0.320;
    // }
    setupDamage() {
        // Building damage;
        this.entityDamage[entity_type_1.EntityType.WOOD_SPIKE] = 10;
        this.entityDamage[entity_type_1.EntityType.STONE_SPIKE] = 20;
        this.entityDamage[entity_type_1.EntityType.GOLD_SPIKE] = 30;
        this.entityDamage[entity_type_1.EntityType.DIAMOND_SPIKE] = 40;
        this.entityDamage[entity_type_1.EntityType.AMETHYST_SPIKE] = 50;
        this.entityDamage[entity_type_1.EntityType.REIDITE_SPIKE] = 60;
        this.entityDamage[entity_type_1.EntityType.WOOD_DOOR_SPIKE] = 5;
        this.entityDamage[entity_type_1.EntityType.STONE_DOOR_SPIKE] = 10;
        this.entityDamage[entity_type_1.EntityType.GOLD_DOOR_SPIKE] = 15;
        this.entityDamage[entity_type_1.EntityType.DIAMOND_DOOR_SPIKE] = 20;
        this.entityDamage[entity_type_1.EntityType.AMETHYST_DOOR_SPIKE] = 25;
        this.entityDamage[entity_type_1.EntityType.REIDITE_DOOR_SPIKE] = 30;
        this.entityOnHitDamage[entity_type_1.EntityType.WOOD_SPIKE] = this.config.wood_spike_damage ?? 2;
        this.entityOnHitDamage[entity_type_1.EntityType.STONE_SPIKE] = this.config.stone_spike_damage ?? 2;
        this.entityOnHitDamage[entity_type_1.EntityType.GOLD_SPIKE] = this.config.gold_spike_damage ?? 3;
        this.entityOnHitDamage[entity_type_1.EntityType.DIAMOND_SPIKE] = this.config.diamond_spike_damage ?? 4;
        this.entityOnHitDamage[entity_type_1.EntityType.AMETHYST_SPIKE] = this.config.amethyst_spike_damage ?? 4;
        this.entityOnHitDamage[entity_type_1.EntityType.REIDITE_SPIKE] = this.config.reidite_spike_damage ?? 5;
        this.entityOnHitDamage[entity_type_1.EntityType.WOOD_DOOR_SPIKE] = this.config.wood_spike_door_damage ?? 1;
        this.entityOnHitDamage[entity_type_1.EntityType.STONE_DOOR_SPIKE] = this.config.stone_spike_door_damage ?? 2;
        this.entityOnHitDamage[entity_type_1.EntityType.GOLD_DOOR_SPIKE] = this.config.gold_spike_door_damage ?? 2;
        this.entityOnHitDamage[entity_type_1.EntityType.DIAMOND_DOOR_SPIKE] = this.config.diamond_spike_door_damage ?? 3;
        this.entityOnHitDamage[entity_type_1.EntityType.AMETHYST_DOOR_SPIKE] = this.config.amethyst_spike_door_damage ?? 3;
        this.entityOnHitDamage[entity_type_1.EntityType.REIDITE_DOOR_SPIKE] = this.config.reidite_spike_door_damage ?? 4;
        this.entityOnHitDamage[entity_type_1.EntityType.EMERALD_MACHINE] = 7;
        // Seed damage
        this.entityDamage[entity_type_1.EntityType.THORNBUSH_MOB] = 40;
        // Forest mobs damage
        this.entityDamage[entity_type_1.EntityType.WOLF] = this.config.damage_wolf ?? 40;
        this.entityDamage[entity_type_1.EntityType.SPIDER] = this.config.damage_spider ?? 30;
        this.entityDamage[entity_type_1.EntityType.BOAR] = this.config.damage_boar ?? 50;
        this.entityDamage[entity_type_1.EntityType.HAWK] = this.config.damage_hawk ?? 40;
        this.entityDamage[entity_type_1.EntityType.CRAB] = this.config.damage_crab ?? 35;
        this.entityDamage[entity_type_1.EntityType.CRAB_BOSS] = this.config.damage_king_crab ?? 80;
        // Winter mobs damage
        this.entityDamage[entity_type_1.EntityType.FOX] = this.config.damage_fox ?? 25;
        this.entityDamage[entity_type_1.EntityType.BEAR] = this.config.damage_bear ?? 60;
        this.entityDamage[entity_type_1.EntityType.MAMMOTH] = this.config.damage_mammoth ?? 70;
        this.entityDamage[entity_type_1.EntityType.BABY_MAMMOTH] = this.config.damage_baby_mammoth ?? 50;
        this.entityDamage[entity_type_1.EntityType.DRAGON] = this.config.damage_dragon ?? 85;
        this.entityDamage[entity_type_1.EntityType.BABY_DRAGON] = this.config.damage_baby_dragon ?? 30;
        // Desert mobs damage
        this.entityDamage[entity_type_1.EntityType.VULTURE] = this.config.damage_vulture ?? 45;
        this.entityDamage[entity_type_1.EntityType.SAND_WORM] = this.config.damage_sand_worm ?? 60;
        // Lava mobs damage
        this.entityDamage[entity_type_1.EntityType.LAVA_DRAGON] = this.config.damage_lava_dragon ?? 90;
        this.entityDamage[entity_type_1.EntityType.BABY_LAVA] = this.config.damage_baby_lava ?? 70;
        this.entityDamage[entity_type_1.EntityType.FLAME] = this.config.damage_flame ?? 50;
        // Ocean mobs damage
        this.entityDamage[entity_type_1.EntityType.KRAKEN] = this.config.damage_kraken ?? 80;
        this.entityDamage[entity_type_1.EntityType.PIRANHA] = this.config.damage_piranha ?? 40;
    }
    setupRadius() {
        this.entityRadius[entity_type_1.EntityType.WOOD_WALL] = 45;
        this.entityRadius[entity_type_1.EntityType.STONE_WALL] = 45;
        this.entityRadius[entity_type_1.EntityType.GOLD_WALL] = 45;
        this.entityRadius[entity_type_1.EntityType.DIAMOND_WALL] = 45;
        this.entityRadius[entity_type_1.EntityType.AMETHYST_WALL] = 45;
        this.entityRadius[entity_type_1.EntityType.REIDITE_WALL] = 45;
        this.entityRadius[entity_type_1.EntityType.WOOD_DOOR] = 45;
        this.entityRadius[entity_type_1.EntityType.STONE_DOOR] = 45;
        this.entityRadius[entity_type_1.EntityType.GOLD_DOOR] = 45;
        this.entityRadius[entity_type_1.EntityType.DIAMOND_DOOR] = 45;
        this.entityRadius[entity_type_1.EntityType.AMETHYST_DOOR] = 45;
        this.entityRadius[entity_type_1.EntityType.REIDITE_DOOR] = 45;
        this.entityRadius[entity_type_1.EntityType.WOOD_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.STONE_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.GOLD_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.DIAMOND_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.AMETHYST_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.REIDITE_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.WOOD_DOOR_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.STONE_DOOR_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.GOLD_DOOR_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.DIAMOND_DOOR_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.AMETHYST_DOOR_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.REIDITE_DOOR_SPIKE] = 35;
        this.entityRadius[entity_type_1.EntityType.STONE_EXTRACTOR] = 45;
        this.entityRadius[entity_type_1.EntityType.GOLD_EXTRACTOR] = 45;
        this.entityRadius[entity_type_1.EntityType.DIAMOND_EXTRACTOR] = 45;
        this.entityRadius[entity_type_1.EntityType.AMETHYST_EXTRACTOR] = 45;
        this.entityRadius[entity_type_1.EntityType.REIDITE_EXTRACTOR] = 45;
        this.entityRadius[entity_type_1.EntityType.BERRY_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.WHEAT_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.PUMPKIN_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.CARROT_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.TOMATO_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.THORNBUSH_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.GARLIC_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.WATERMELON_SEED] = 40;
        this.entityRadius[entity_type_1.EntityType.RESURRECTION] = 55;
        this.entityRadius[entity_type_1.EntityType.EMERALD_MACHINE] = 55;
        this.entityRadius[entity_type_1.EntityType.WORKBENCH] = 35;
        this.entityRadius[entity_type_1.EntityType.WINDMILL] = 50;
        this.entityRadius[entity_type_1.EntityType.FURNACE] = 55;
        this.entityRadius[entity_type_1.EntityType.WELL] = 60;
        this.entityRadius[entity_type_1.EntityType.BREAD_OVEN] = 60;
        this.entityRadius[entity_type_1.EntityType.TOTEM] = 55;
        this.entityRadius[entity_type_1.EntityType.WOLF] = 40;
        this.entityRadius[entity_type_1.EntityType.SAND_WORM] = 40;
        this.entityRadius[entity_type_1.EntityType.SPIDER] = 28;
        this.entityRadius[entity_type_1.EntityType.RABBIT] = 45;
        this.entityRadius[entity_type_1.EntityType.BOAR] = 65;
        this.entityRadius[entity_type_1.EntityType.KRAKEN] = 60;
        this.entityRadius[entity_type_1.EntityType.DRAGON] = 50;
        this.entityRadius[entity_type_1.EntityType.LAVA_DRAGON] = 60;
    }
    setupCollide() {
        // this.entityCollide[EntityType.WOOD_WALL] = true;
        // this.entityCollide[EntityType.STONE_WALL] = true;
        // this.entityCollide[EntityType.GOLD_WALL] = true;
        // this.entityCollide[EntityType.DIAMOND_WALL] = true;
        // this.entityCollide[EntityType.AMETHYST_WALL] = true;
        // this.entityCollide[EntityType.REIDITE_WALL] = true;
        //
        // this.entityCollide[EntityType.WOOD_DOOR] = true;
        // this.entityCollide[EntityType.STONE_DOOR] = true;
        // this.entityCollide[EntityType.GOLD_DOOR] = true;
        // this.entityCollide[EntityType.DIAMOND_DOOR] = true;
        // this.entityCollide[EntityType.AMETHYST_DOOR] = true;
        // this.entityCollide[EntityType.REIDITE_DOOR] = true;
        //
        // this.entityCollide[EntityType.WOOD_SPIKE] = true;
        // this.entityCollide[EntityType.STONE_SPIKE] = true;
        // this.entityCollide[EntityType.GOLD_SPIKE] = true;
        // this.entityCollide[EntityType.DIAMOND_SPIKE] = true;
        // this.entityCollide[EntityType.AMETHYST_SPIKE] = true;
        // this.entityCollide[EntityType.REIDITE_SPIKE] = true;
        //
        // this.entityCollide[EntityType.TOTEM] = true;
        //
        // this.entityCollide[EntityType.WOOD_DOOR_SPIKE] = true;
        // this.entityCollide[EntityType.STONE_DOOR_SPIKE] = true;
        // this.entityCollide[EntityType.GOLD_DOOR_SPIKE] = true;
        // this.entityCollide[EntityType.DIAMOND_DOOR_SPIKE] = true;
        // this.entityCollide[EntityType.AMETHYST_DOOR_SPIKE] = true;
        // this.entityCollide[EntityType.REIDITE_DOOR_SPIKE] = true;
        //
        // this.entityCollide[EntityType.STONE_EXTRACTOR] = true;
        // this.entityCollide[EntityType.GOLD_EXTRACTOR] = true;
        // this.entityCollide[EntityType.DIAMOND_EXTRACTOR] = true;
        // this.entityCollide[EntityType.AMETHYST_EXTRACTOR] = true;
        // this.entityCollide[EntityType.REIDITE_EXTRACTOR] = true;
        //
        // this.entityCollide[EntityType.RESURRECTION] = true;
        // this.entityCollide[EntityType.EMERALD_MACHINE] = true;
        // this.entityCollide[EntityType.WINDMILL] = true;
        // this.entityCollide[EntityType.WELL] = true;
        // this.entityCollide[EntityType.BREAD_OVEN] = true;
        // this.entityCollide[EntityType.WORKBENCH] = true;
        // this.entityCollide[EntityType.CHEST] = true;
        // this.entityCollide[EntityType.FURNACE] = true;
    }
    setupHealth() {
        this.health[entity_type_1.EntityType.PLAYER] = 200;
        this.health[entity_type_1.EntityType.FIRE] = 150;
        this.health[entity_type_1.EntityType.WORKBENCH] = 300;
        this.health[entity_type_1.EntityType.BERRY_SEED] = 700;
        this.health[entity_type_1.EntityType.WOOD_WALL] = this.config.wood_wall_life ?? 1000;
        this.health[entity_type_1.EntityType.WOOD_SPIKE] = this.config.wood_spike_life ?? 150;
        this.health[entity_type_1.EntityType.BIG_FIRE] = 400;
        this.health[entity_type_1.EntityType.STONE_WALL] = this.config.stone_wall_life ?? 1500;
        this.health[entity_type_1.EntityType.GOLD_WALL] = this.config.gold_wall_life ?? 2000;
        this.health[entity_type_1.EntityType.DIAMOND_WALL] = this.config.diamond_wall_life ?? 2500;
        this.health[entity_type_1.EntityType.WOOD_DOOR] = this.config.wood_door_life ?? 1000;
        this.health[entity_type_1.EntityType.CHEST] = 500;
        this.health[entity_type_1.EntityType.STONE_SPIKE] = this.config.stone_spike_life ?? 300;
        this.health[entity_type_1.EntityType.GOLD_SPIKE] = this.config.gold_spike_life ?? 600;
        this.health[entity_type_1.EntityType.DIAMOND_SPIKE] = this.config.diamond_spike_life ?? 1200;
        this.health[entity_type_1.EntityType.STONE_DOOR] = this.config.stone_door_life ?? 1500;
        this.health[entity_type_1.EntityType.GOLD_DOOR] = this.config.gold_door_life ?? 2000;
        this.health[entity_type_1.EntityType.DIAMOND_DOOR] = this.config.diamond_door_life ?? 2500;
        this.health[entity_type_1.EntityType.FURNACE] = 1000;
        this.health[entity_type_1.EntityType.AMETHYST_WALL] = this.config.amethyst_wall_life ?? 3500;
        this.health[entity_type_1.EntityType.AMETHYST_SPIKE] = this.config.amethyst_spike_life ?? 2400;
        this.health[entity_type_1.EntityType.AMETHYST_DOOR] = this.config.amethyst_door_life ?? 3500;
        this.health[entity_type_1.EntityType.RESURRECTION] = 200;
        this.health[entity_type_1.EntityType.EMERALD_MACHINE] = 1000;
        this.health[entity_type_1.EntityType.STONE_EXTRACTOR] = 2000;
        this.health[entity_type_1.EntityType.GOLD_EXTRACTOR] = 2000;
        this.health[entity_type_1.EntityType.DIAMOND_EXTRACTOR] = 2000;
        this.health[entity_type_1.EntityType.AMETHYST_EXTRACTOR] = 2000;
        this.health[entity_type_1.EntityType.REIDITE_EXTRACTOR] = 2000;
        this.health[entity_type_1.EntityType.TOTEM] = 300;
        this.health[entity_type_1.EntityType.BRIDGE] = 1000;
        this.health[entity_type_1.EntityType.WHEAT_SEED] = 700;
        this.health[entity_type_1.EntityType.WINDMILL] = 2000;
        this.health[entity_type_1.EntityType.PLOT] = this.config.plot_life ?? 2000;
        this.health[entity_type_1.EntityType.GARLAND] = 1e9;
        this.health[entity_type_1.EntityType.BREAD_OVEN] = 2000;
        this.health[entity_type_1.EntityType.WELL] = 1000;
        this.health[entity_type_1.EntityType.SIGN] = 200;
        this.health[entity_type_1.EntityType.PUMPKIN_SEED] = 700;
        this.health[entity_type_1.EntityType.ROOF] = 1000;
        this.health[entity_type_1.EntityType.GARLIC_SEED] = 700;
        this.health[entity_type_1.EntityType.THORNBUSH_SEED] = 700;
        this.health[entity_type_1.EntityType.BED] = 400;
        this.health[entity_type_1.EntityType.TOMATO_SEED] = 700;
        this.health[entity_type_1.EntityType.CARROT_SEED] = 700;
        this.health[entity_type_1.EntityType.WOOD_DOOR_SPIKE] = this.config.wood_spike_door_life ?? 100;
        this.health[entity_type_1.EntityType.STONE_DOOR_SPIKE] = this.config.stone_spike_door_life ?? 200;
        this.health[entity_type_1.EntityType.GOLD_DOOR_SPIKE] = this.config.gold_spike_door_life ?? 400;
        this.health[entity_type_1.EntityType.DIAMOND_DOOR_SPIKE] = this.config.diamond_spike_door_life ?? 800;
        this.health[entity_type_1.EntityType.AMETHYST_DOOR_SPIKE] = this.config.amethyst_spike_door_life ?? 1600;
        this.health[entity_type_1.EntityType.REIDITE_WALL] = this.config.reidite_wall_life ?? 4000;
        this.health[entity_type_1.EntityType.REIDITE_DOOR] = this.config.reidite_wall_life ?? 4000;
        this.health[entity_type_1.EntityType.REIDITE_SPIKE] = this.config.reidite_spike_life ?? 3000;
        this.health[entity_type_1.EntityType.REIDITE_DOOR_SPIKE] = this.config.reidite_spike_door_life ?? 2000;
        this.health[entity_type_1.EntityType.WATERMELON_SEED] = 400;
        this.health[entity_type_1.EntityType.ALOE_VERA_SEED] = 400;
        this.health[entity_type_1.EntityType.TOWER] = 2000;
        this.health[entity_type_1.EntityType.WOLF] = this.config.wolf_life ?? 230;
        this.health[entity_type_1.EntityType.SPIDER] = this.config.spider_life ?? 240;
        this.health[entity_type_1.EntityType.FOX] = this.config.fox_life ?? 235;
        this.health[entity_type_1.EntityType.BEAR] = this.config.bear_life ?? 220;
        this.health[entity_type_1.EntityType.DRAGON] = this.config.dragon_life ?? 225;
        this.health[entity_type_1.EntityType.PIRANHA] = this.config.piranha_life ?? 290;
        this.health[entity_type_1.EntityType.KRAKEN] = this.config.kraken_life ?? 240;
        this.health[entity_type_1.EntityType.CRAB] = this.config.crab_life ?? 320;
        this.health[entity_type_1.EntityType.FLAME] = this.config.flame_life ?? 240;
        this.health[entity_type_1.EntityType.LAVA_DRAGON] = this.config.lava_dragon_life ?? 245;
        this.health[entity_type_1.EntityType.BOAR] = this.config.boar_life ?? 300;
        this.health[entity_type_1.EntityType.CRAB_BOSS] = this.config.king_crab_life ?? 240;
        this.health[entity_type_1.EntityType.BABY_DRAGON] = this.config.baby_dragon_life ?? 250;
        this.health[entity_type_1.EntityType.BABY_LAVA] = this.config.baby_lava_life ?? 270;
        this.health[entity_type_1.EntityType.HAWK] = this.config.hawk_life ?? 300;
        this.health[entity_type_1.EntityType.VULTURE] = this.config.vulture_life ?? 250;
        this.health[entity_type_1.EntityType.SAND_WORM] = this.config.sand_worm_life ?? 250;
        this.health[entity_type_1.EntityType.BABY_MAMMOTH] = this.config.baby_mammoth_life ?? 230;
        this.health[entity_type_1.EntityType.MAMMOTH] = this.config.mammoth_life ?? 230;
        this.health[entity_type_1.EntityType.RABBIT] = this.config.rabbit_life ?? 320;
        this.health[entity_type_1.EntityType.TREASURE_CHEST] = this.config.treasure_life ?? 300;
        this.health[entity_type_1.EntityType.DEAD_BOX] = 300;
        this.health[entity_type_1.EntityType.CRATE] = 30;
        this.health[entity_type_1.EntityType.GIFT] = 30;
        this.health[entity_type_1.EntityType.PENGUIN] = this.config.penguin_life ?? 320;
    }
}
exports.ConfigSystem = ConfigSystem;
