"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnimalBoxes = void 0;
const entity_type_1 = require("./types/entity.type");
const cosmetics_1 = require("./cosmetics");
exports.AnimalBoxes = [];
exports.AnimalBoxes[entity_type_1.EntityType.WOLF] = cosmetics_1.BOX.BOX_OF_THE_WOLF;
exports.AnimalBoxes[entity_type_1.EntityType.RABBIT] = cosmetics_1.BOX.BOX_OF_THE_RABBIT;
exports.AnimalBoxes[entity_type_1.EntityType.SPIDER] = cosmetics_1.BOX.BOX_OF_THE_SPIDER;
exports.AnimalBoxes[entity_type_1.EntityType.HAWK] = cosmetics_1.BOX.BOX_OF_THE_HAWK;
exports.AnimalBoxes[entity_type_1.EntityType.BOAR] = cosmetics_1.BOX.BOX_OF_THE_BOAR;
exports.AnimalBoxes[entity_type_1.EntityType.CRAB] = cosmetics_1.BOX.BOX_OF_THE_CRAB;
exports.AnimalBoxes[entity_type_1.EntityType.CRAB_BOSS] = cosmetics_1.BOX.BOX_OF_THE_KING_CRAB;
exports.AnimalBoxes[entity_type_1.EntityType.FOX] = cosmetics_1.BOX.BOX_OF_THE_FOX;
exports.AnimalBoxes[entity_type_1.EntityType.BEAR] = cosmetics_1.BOX.BOX_OF_THE_BEAR;
exports.AnimalBoxes[entity_type_1.EntityType.PENGUIN] = cosmetics_1.BOX.BOX_OF_THE_PENGUIN;
exports.AnimalBoxes[entity_type_1.EntityType.MAMMOTH] = cosmetics_1.BOX.BOX_OF_THE_MAMMOTH;
exports.AnimalBoxes[entity_type_1.EntityType.BABY_MAMMOTH] = cosmetics_1.BOX.BOX_OF_THE_BABY_MAMMOTH;
exports.AnimalBoxes[entity_type_1.EntityType.DRAGON] = cosmetics_1.BOX.BOX_OF_THE_DRAGON;
exports.AnimalBoxes[entity_type_1.EntityType.BABY_DRAGON] = cosmetics_1.BOX.BOX_OF_THE_BABY_DRAGON;
exports.AnimalBoxes[entity_type_1.EntityType.FLAME] = cosmetics_1.BOX.BOX_OF_THE_FIRE_MOB;
exports.AnimalBoxes[entity_type_1.EntityType.LAVA_DRAGON] = cosmetics_1.BOX.BOX_OF_THE_LAVA_DRAGON;
exports.AnimalBoxes[entity_type_1.EntityType.BABY_LAVA] = cosmetics_1.BOX.BOX_OF_THE_BABY_LAVA;
exports.AnimalBoxes[entity_type_1.EntityType.VULTURE] = cosmetics_1.BOX.BOX_OF_THE_VULTURE;
exports.AnimalBoxes[entity_type_1.EntityType.SAND_WORM] = cosmetics_1.BOX.BOX_OF_THE_SANDWORM;
exports.AnimalBoxes[entity_type_1.EntityType.PIRANHA] = cosmetics_1.BOX.BOX_OF_THE_PIRANHA;
exports.AnimalBoxes[entity_type_1.EntityType.KRAKEN] = cosmetics_1.BOX.BOX_OF_THE_KRAKEN;
