"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DeathReason = void 0;
var DeathReason;
(function (DeathReason) {
    DeathReason[DeathReason["UNKNOWN"] = 0] = "UNKNOWN";
    DeathReason[DeathReason["STARVE"] = 1] = "STARVE";
    DeathReason[DeathReason["COLD"] = 2] = "COLD";
    DeathReason[DeathReason["PLAYER"] = 3] = "PLAYER";
    DeathReason[DeathReason["FIRE"] = 4] = "FIRE";
    DeathReason[DeathReason["SPIDER"] = 5] = "SPIDER";
    DeathReason[DeathReason["WOLF"] = 6] = "WOLF";
    DeathReason[DeathReason["FOX"] = 7] = "FOX";
    DeathReason[DeathReason["BEAR"] = 8] = "BEAR";
    DeathReason[DeathReason["DRAGON"] = 9] = "DRAGON";
    DeathReason[DeathReason["SPIKE"] = 10] = "SPIKE";
    DeathReason[DeathReason["GHOST"] = 11] = "GHOST";
    DeathReason[DeathReason["RAW_FOOD"] = 12] = "RAW_FOOD";
    DeathReason[DeathReason["WATER"] = 13] = "WATER";
    DeathReason[DeathReason["OXYGEN"] = 14] = "OXYGEN";
    DeathReason[DeathReason["PIRANHA"] = 15] = "PIRANHA";
    DeathReason[DeathReason["KRAKEN"] = 16] = "KRAKEN";
    DeathReason[DeathReason["SUN_LIGHT"] = 17] = "SUN_LIGHT";
    DeathReason[DeathReason["GARLIC_POCKET"] = 18] = "GARLIC_POCKET";
    DeathReason[DeathReason["GARLIC"] = 19] = "GARLIC";
    DeathReason[DeathReason["ATE_GARLIC"] = 20] = "ATE_GARLIC";
    DeathReason[DeathReason["THORNBUSH"] = 21] = "THORNBUSH";
    DeathReason[DeathReason["CRAB"] = 22] = "CRAB";
    DeathReason[DeathReason["WARM"] = 23] = "WARM";
    DeathReason[DeathReason["LAVA"] = 24] = "LAVA";
    DeathReason[DeathReason["FLAME_MOB"] = 25] = "FLAME_MOB";
    DeathReason[DeathReason["LAVA_DRAGON"] = 26] = "LAVA_DRAGON";
    DeathReason[DeathReason["BOAR"] = 27] = "BOAR";
    DeathReason[DeathReason["CRAB_BOSS"] = 28] = "CRAB_BOSS";
    DeathReason[DeathReason["BABY_DRAGON"] = 29] = "BABY_DRAGON";
    DeathReason[DeathReason["BABY_LAVA"] = 30] = "BABY_LAVA";
    DeathReason[DeathReason["HAWK"] = 31] = "HAWK";
    DeathReason[DeathReason["CACTUS"] = 32] = "CACTUS";
    DeathReason[DeathReason["VULTURE"] = 33] = "VULTURE";
    DeathReason[DeathReason["SAND_WORM"] = 34] = "SAND_WORM";
    DeathReason[DeathReason["SAND"] = 35] = "SAND";
    DeathReason[DeathReason["EMERALD"] = 36] = "EMERALD";
    DeathReason[DeathReason["BABY_MAMMOTH"] = 37] = "BABY_MAMMOTH";
    DeathReason[DeathReason["MAMMOTH"] = 38] = "MAMMOTH";
    DeathReason[DeathReason["BLIZZARD"] = 39] = "BLIZZARD";
})(DeathReason || (exports.DeathReason = DeathReason = {}));
