"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TileType = void 0;
var TileType;
(function (TileType) {
    TileType["RIVER"] = "r";
    TileType["TREE"] = "t";
    TileType["BIG_TREE"] = "b";
    TileType["WINTER_TREE"] = "f";
    TileType["STONE"] = "s";
    TileType["GOLD"] = "g";
    TileType["DIAMOND"] = "d";
    TileType["AMETHYST"] = "a";
    TileType["REIDITE"] = "re";
    TileType["EMERALD"] = "m";
    TileType["BERRY"] = "p";
    TileType["CACTUS"] = "c";
    TileType["LAVA"] = "la";
    TileType["SAND"] = "iblk";
})(TileType || (exports.TileType = TileType = {}));
